export const GET_RANDOM_CLUES = "GET_RANDOM_CLUES";
export const GET_RANDOM_CLUES_SUCCESS = "GET_RANDOM_CLUES_SUCCESS";
export const GET_RANDOM_CLUES_ERROR = "GET_RANDOM_CLUES_ERROR";

export const PAGE_BACK = "PAGE_BACK";
export const PAGE_FORWARD = "PAGE_FORWARD";

export const TOGGLE_ACTIVE_GAME = "TOGGLE_ACTIVE_GAME";
export const TOGGLE_ANSWER_VISIBLE = "TOGGLE_ANSWER_VISIBLE";
